#!/bin/bash -e

apt_packages_list=(
    emacs
    emacs-mozc-bin
    cmus
    guake
    arp-scan
    dconf-cli
    dconf-editor
    tree
    gnome-tweaks
    mysql-client
    python3-pip
    xsel
    pinta
    fontforge
    fonts-migmix
    python-virtualenv
    python3-venv
    net-tools
    vim
    vagrant
    virtualbox
    fonts-noto-color-emoji
    fish
    graphviz
    default-jre
    ansible
    imagemagick
    htop
    vlc
    libreoffice
    libvirt-clients
    libvirt-daemon
    qemu-kvm
)

sudo apt-get install -qq "${apt_packages_list[@]}"

mkdir -p ~/.config/autostart
test -f /usr/share/applications/guake.desktop && \
    ln -sf /usr/share/applications/guake.desktop ~/.config/autostart/guake.desktop
