#!/bin/bash -eux

apt_packages_list=(
    emacs
    emacs-mozc-bin
    cmus
    guake
    arp-scan
    dconf-cli
    dconf-editor
    tree
    gnome-tweaks
    mysql-client
    xsel
    pinta
    net-tools
    vim
    vagrant
    virtualbox
    virtualbox-guest-additions-iso
    fonts-noto-color-emoji
    graphviz
    default-jre
    imagemagick
    htop
    vlc
    libreoffice
    libvirt-clients
    libvirt-daemon
    virt-manager
    qemu-kvm
    nmap
    jq
    ibus-mozc
    mozc-utils-gui
    piper
)

sudo apt-get install -qq "${apt_packages_list[@]}"

mkdir -p ~/.config/autostart

autostart_package=(guake.desktop emacs.desktop google-chrome.desktop)

for package in "${autostart_package[@]}"; do
    test -f /usr/share/applications/"${package}" && \
        ln -sf /usr/share/applications/"${package}" ~/.config/autostart/"${package}"
done
