#!/bin/bash -e

[[ $(id -u) -eq 0 ]] || exec sudo -E "$0"

build_dependencies=(apt-transport-https ca-certificates curl gnupg-agent software-properties-common)

echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu eoan stable" > \
     /etc/apt/sources.list.d/docker.list

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

apt-get -qq update
apt-get -qq install "${build_dependencies[@]}"
apt-get -qq install docker-ce docker-ce-cli containerd.io

# https://docs.docker.com/engine/install/linux-postinstall/
if logname &> /dev/null; then
    usermod -aG docker "$(logname)"
fi
