#!/bin/bash -eux

if ! hash brew 2> /dev/null; then
    case $(uname --kernel-name) in
        Linux)
            hash apt-get 2> /dev/null && sudo apt-get install -qq build-essential curl file git ruby
            yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
            test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
            test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            ;;
        Darwin)
            yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
            ;;
    esac
fi

tap_list=(
    aws/tap
)

for tap in "${tap_list[@]}"; do
    brew tap "${tap}"
done

package_list=(
    awscli
    dep
    git
    go
    n
    pipenv
    rbenv
    tmux
    shellcheck
    prettier
    tfenv
    tflint
    kubectl
    helm
    direnv
    gibo
    cquery
    yarn
    yarn-completion
    minikube
    cfssl
    aws-sam-cli
    circleci
    terraformer
    hub
    hadolint
    nektos/tap/act
    cmake
    bison
    flex
    ansible
    ansible-lint
    docker-compose
    packer
    git-secrets
    awsebcli
    gh
    amazon-ecs-cli
    aws/tap/copilot-cli
)

brew install --force --display-times "${package_list[@]}"
