#!/bin/bash -eux

cd "$(dirname "$0")"

if ! hash brew 2> /dev/null; then
    case $(uname --kernel-name) in
        Linux)
            hash apt-get 2> /dev/null && sudo apt-get install -qq build-essential curl file git ruby
            yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
            test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
            test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            ;;
        Darwin)
            yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
            ;;
    esac
fi

brew bundle install --file=../Brewfile
