#!/bin/bash -eux

LANG=C xdg-user-dirs-update --force

if [ -d /usr/share/gnome-shell/extensions/desktop-icons@csoriano/ ]; then
    sudo rm -rf /usr/share/gnome-shell/extensions/desktop-icons@csoriano
fi
