#!/bin/bash -eux

LANG=C xdg-user-dirs-update --force

# autostart xmodmap
mkdir -p ~/.config/autostart
cat <<EOF > ~/.config/autostart/xmodmap.desktop
[Desktop Entry]
Name[en_US]=xmodmap
Comment[en_US]=xmodmap ~/.xmodmaprc
Exec=/usr/bin/xmodmap .xmodmaprc
X-GNOME-Autostart-enabled=true
Type=Application
EOF

if [ -d /usr/share/gnome-shell/extensions/desktop-icons@csoriano/ ]; then
    sudo rm -rf /usr/share/gnome-shell/extensions/desktop-icons@csoriano
fi
