;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-star
	markdown-cycle
	tabbar-forward-tab
	undo-tree-visualize
	xref-find-apropos
	))

(setq mc/cmds-to-run-once
      '(
	markdown-exdent-or-delete
	mouse-drag-secondary
	))
