;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        markdown-cycle
        tabbar-forward-tab
        undo-tree-visualize
        ))

(setq mc/cmds-to-run-once
      '(
        markdown-exdent-or-delete
        mouse-drag-secondary
        ))
