#!/bin/bash -eu

function enable_sudo() {
    username="$(logname 2> /dev/null || echo "${USER}")"
    cat <<EOF | sudo tee /etc/sudoers.d/"${username}" > /dev/null
${username} ALL=NOPASSWD: ALL
EOF
}

function install_build_dependencies() {
    hash apt-get &> /dev/null && \
        sudo apt-get install -qq git curl && \
        return
}

enable_sudo
install_build_dependencies

if ! cd ~/.dotfiles &> /dev/null; then
    git clone https://github.com/maya2250/dotfiles.git ~/.dotfiles
    cd ~/.dotfiles
fi

find bootstrap/ -type f -executable -exec bash -eux {} \;

git remote set-url origin git@github.com:maya2250/dotfiles.git
