set number
set autoindent
set incsearch
set autoread
set showmatch
set smartindent
set shiftwidth=2 tabstop=2 expandtab

scriptencoding utf-8
set encoding=utf-8

:syntax on
colorscheme desert

" invalid arrow keys
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>
