set number             " line number
set autoindent         " auto indentation
set incsearch          " incremental search
set autoread           " auto reload
set showmatch          " show matching parenthesis
set smartindent        " 
set shiftwidth=2       " set shift moving width
set tabstop=4          " tab width

set list               " show invisible character

scriptencoding utf-8
set encoding=utf-8

:syntax on
colorscheme jellybeans

" invalid arrow keys
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>
