version: 2.1

jobs:
  build:
    docker:
      - image: maya2250/dotfiles:ubuntu-19.10
    working_directory: ~/project
    steps:
      - checkout
      - run: sudo apt-get update -qq
      - run:
          command: ansible-playbook provisioning/site.yml
          no_output_timeout: 1h
