#!/usr/bin/env bash

set -e

LANG=C xdg-user-dirs-update --force

# autostart xmodmap
mkdir -p ~/.config/autostart
cat <<EOF > ~/.config/autostart/xmodmap.desktop
[Desktop Entry]
Name[en_US]=xmodmap
Comment[en_US]=xmodmap ~/.xmodmaprc
Exec=/usr/bin/xmodmap .xmodmaprc
X-GNOME-Autostart-enabled=true
Type=Application
EOF

# https://github.com/tmux-plugins/tpm#installation
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
