#!/usr/bin/env bash

set -e

[[ $(id -u) -eq 0 ]] || exec sudo -E "$0"

BUILD_DEPENDENCIES=(apt-transport-https ca-certificates curl gnupg-agent software-properties-common)

apt-get -qq update
apt-get -qq install "${BUILD_DEPENDENCIES[@]}"
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   disco \
   stable"

apt-get -qq update
apt-get -qq install docker-ce docker-ce-cli containerd.io
DOCKER_VERSION=$(apt-cache madison docker-ce | head -1 | cut -d'|' -f2 | tr -d '[:space:]')
apt-get -qq install docker-ce="${DOCKER_VERSION}" docker-ce-cli="${DOCKER_VERSION}" containerd.io

# docker-compose
curl -fsSL "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
curl -sL https://raw.githubusercontent.com/docker/compose/1.24.1/contrib/completion/bash/docker-compose \
     -o /etc/bash_completion.d/docker-compose

# https://docs.docker.com/install/linux/linux-postinstall/
if ! grep --quiet docker /etc/group; then
    groupadd docker
    usermod -aG docker "$(logname)"
fi
