#!/usr/bin/env bash

pip3 install --user powerline-status

# ref: https://powerline.readthedocs.io/en/latest/installation/linux.html#fonts-installation
DIR=$(mktemp -d)
pushd ${DIR}
curl -sSLO https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
curl -sSLO https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf

mkdir -p ~/.local/share/fonts/
mv PowerlineSymbols.otf ~/.local/share/fonts/

fc-cache -vf ~/.local/share/fonts/

mkdir -p ~/.config/fontconfig/conf.d/
mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/

popd
rm -fr ${DIR}
