#!/usr/bin/env bash

set -e

[[ $(id -u) -eq 0 ]] || exec sudo -E "$0"

cd $(dirname $0)

DEB_DIR=$(mktemp -d)
DEB_PACKAGES=$(cat deb_packages.txt)

pushd ${DEB_DIR} > /dev/null
for url in ${DEB_PACKAGES[@]}; do
    curl -sSL -O ${url}
done
popd > /dev/null

apt-get install -qqf ${DEB_DIR}/*.deb
rm -fr ${DEB_DIR}
