#!/usr/bin/env bash

set -e

cd "$(dirname "$0")"

find dconf.d -type f | while read -r file; do
    DIR_PATH=$(echo "${file}" | sed -e "s/dconf.d//" -e "s/.conf/\//")
    dconf load "${DIR_PATH}" < "${file}"
done
