FROM ubuntu:20.10
LABEL maintainer="maya2250.dev@gmail.com"

ARG USER="guest"
ARG LINUXBREW_DEPENDENCIES="build-essential curl file git ruby"
ARG BUILD_DEPENDENCIES="language-pack-en sudo"

ENV DEBIAN_FRONTEND noninteractive

RUN set -ux && \
        useradd -m -s /bin/bash ${USER} && \
        echo "${USER}:password" | chpasswd && \
        apt-get update -qq && \
        apt-get install -qq ${LINUXBREW_DEPENDENCIES} ${BUILD_DEPENDENCIES} && \
        echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
        echo 'Set disable_coredump false' > /etc/sudo.conf

USER ${USER}
ENV USER ${USER}
WORKDIR /home/${USER}
