;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-star
	markdown-cycle
	org-beginning-of-line
	org-self-insert-command
	tabbar-forward-tab
	undo-tree-visualize
	xref-find-apropos
	xref-find-definitions
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	electric-newline-and-maybe-indent
	markdown-exdent-or-delete
	mouse-drag-secondary
	))
